name: Build and Export Binary

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller

    - name: Build binary with PyInstaller
      run: |
        cd web_app/
        pyinstaller --add-data "web;web" --add-data "c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\eel\eel.js;eel" --exclude keras --exclude tensorflow main.py
     #python -m eel web_app/main.py web_app/web --exclude tensorflow --exclude keras

    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: car-classifier-linux
        path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller
        pip install eel

    - name: Build binary with PyInstaller
      run: |
        cd web_app/
        pyinstaller --add-data "web;web" --add-data "c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\eel\eel.js;eel" --exclude keras --exclude tensorflow main.py
      #python -m eel web_app/main.py web_app/web --exclude tensorflow --exclude keras

    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: car-classifier-windows
        path: dist/
