name: Build and Export Binary

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
        pip install PyInstaller

    - name: Build binary with PyInstaller
      run: |
        cd web_app/
        python -m eel main.py web 

    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: car-classifier-linux
        path: web_app/dist/

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
        pip install PyInstaller
        pip install eel

    - name: Build binary with PyInstaller
      run: |
        cd web_app/
        python -m eel main.py web --add-data "c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\rembg;rembg" --add-data "..\utilities\class_names.py;utilities" --add-data "..\testing\prepare_images.py;testing"
      #pyinstaller --add-data "web;web" --add-data "c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\eel\eel.js;eel" --add-data "c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\rembg;rembg" --add-data "..\utilities\class_names.py;utilities" --add-data "..\testing\prepare_images.py;testing" --exclude keras --exclude tensorflow main.py


    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: car-classifier-windows
        path: web_app/dist/
