name: Dependabot

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates
        uses: dependabot/dependabot-core@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: '/'
          package-ecosystem: 'pip'
          versioning-strategy: 'auto'
          open-pull-requests-limit: 5
